# Site settings
title: Lucky Llama
email: hello@lucky-llama.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: ff6d00
  secondary: b24c00
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Gabi Carpenter
  pic: gabi_carpenter
  position: Director and Producer
  social:
    - title: twitter
      url: "https://twitter.com/gabicarpenter"
    - title: at
      url:  "mailto:gabi@lucky-llama.com"
    - title: youtube
      url: "https://www.youtube.com/user/GabiCarpenter/videos?flow=grid&view=0"

- name: Matt Bostock
  pic: matt_bostock
  position: Web Consultant
  social:
    - title: twitter
      url: "https://twitter.com/mattbostock"
    - title: at
      url:  "mailto:matt@lucky-llama.com"
    - title: github
      url: "https://github.com/mattbostock"

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
